params ["_display"];
(_display displayCTRL 4201) ctrlSetText (cursorTarget getVariable ["2745_DTG",""]);
(_display displayCTRL 4202) ctrlSetText (cursorTarget getVariable ["2745_NAME",""]);
(_display displayCTRL 4203) ctrlSetText (cursorTarget getVariable ["2745_UNIT",""]);
(_display displayCTRL 4204) ctrlSetText (cursorTarget getVariable ["2745_RANK",""]);
(_display displayCTRL 4205) ctrlSetText (cursorTarget getVariable ["2745_CAPTURER",""]);
(_display displayCTRL 4206) ctrlSetText (cursorTarget getVariable ["2745_LOCATION",""]);
(_display displayCTRL 4207) ctrlSetText (cursorTarget getVariable ["2745_CIRCUMSTANCES",""]);
(_display displayCTRL 4208) ctrlSetText (cursorTarget getVariable ["2745_CONDITION",""]);
(_display displayCTRL 4209) ctrlSetText (cursorTarget getVariable ["2745_EQUIPMENT",""]);