_this removeItem '4R_MASCAS';
for "_i" from 1 to 6 do {_this addItemToBackpack "4R_IFAK"};
for "_i" from 1 to 30 do {_this addItemToBackpack "ACE_packingBandage"};
for "_i" from 1 to 20 do {_this addItemToBackpack "ACE_elasticBandage"};
for "_i" from 1 to 60 do {_this addItemToBackpack "ACE_packingBandage"};
for "_i" from 1 to 12 do {_this addItemToBackpack "ACE_tourniquet"};
//for "_i" from 1 to 6 do {_this addItemToBackpack "4R_Blanket"};
for "_i" from 1 to 6 do {_this addItemToBackpack "kat_chestSeal"};
for "_i" from 1 to 6 do {_this addItemToBackpack "kat_ncdKit"};
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_Chemlight_UltraHiOrange"};
_this addItemToBackpack "kat_stretcher";
_this addItemToBackpack "kat_stretcher";
_this addItemToBackpack "UK3CB_BAF_SmokeShellOrange";
//_this addItemToBackpack "FSGm_ItemMedicBagMil";
_this addItemToBackpack "kat_AED";